### ISSUE TITLE
replicate.exceptions.ModelError: name 'latent_dim' is not defined

### ISSUE THREAD

**Issue by charmdew** [mchong6/JoJoGAN#45]
Hello, thank you for your awesome work!

Instead of the pretrained model, I tried to convert the image by uploading a style image with replicate API.
But an error has occured.

![https://user-images.githubusercontent.com/37644126/215038745-eaffd84b-35ed-4744-ae58-ec7a2ecf99f8.png](https://user-images.githubusercontent.com/37644126/215038745-eaffd84b-35ed-4744-ae58-ec7a2ecf99f8.png)

```
Traceback (most recent call last):
  File "C:\\Users\\SSAFY\\PycharmProjects\\JoJoGAN\\jojogan_api.py", line 45, in <module>
    output = version.predict(**inputs)
  File "C:\\Users\\SSAFY\\anaconda3\\envs\\reboot_JoJoGAN\\lib\\site-packages\\replicate\\version.py", line 31, in predict
    raise ModelError(prediction.error)
replicate.exceptions.ModelError: name 'latent_dim' is not defined

```

---
The same error occurs on the demo page.  

![image](https://user-images.githubusercontent.com/37644126/215369383-6729ef1a-9f78-44de-be1c-ed7cdf7c9423.png)

**Comment by chernikovalexey** [comment]
Have you solved it?
